# Generated by Django 2.0.3 on 2018-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.Sub_addon'),
        ),
    ]
