# Generated by Django 2.0.3 on 2018-04-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_reg_pizza_syc_pizza_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='large',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='small',
            new_name='price_price',
        ),
        migrations.AlterField(
            model_name='reg_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='reg_pizza', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='syc_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='syc_pizza', to='orders.Topping'),
        ),
    ]
