# Generated by Django 2.0.3 on 2018-04-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180413_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='price_price',
            new_name='price_small',
        ),
    ]
