# Generated by Django 2.0.3 on 2018-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180414_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
