# Generated by Django 2.0.3 on 2018-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180414_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_pizza',
            name='amount_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
