# Generated by Django 2.0.3 on 2018-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_sub_amount_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='amount_addons',
            field=models.IntegerField(default=1),
        ),
    ]
