# Generated by Django 2.0.3 on 2018-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180422_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_pizza',
            name='amount_toppings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='amount_addons',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='syc_pizza',
            name='amount_toppings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
