# Generated by Django 2.0.3 on 2018-04-30 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_auto_20180422_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addon', models.ManyToManyField(blank=True, related_name='sub', to='orders.Sub_addon')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topping', models.ManyToManyField(blank=True, related_name='pizza', to='orders.Topping')),
            ],
        ),
        migrations.RemoveField(
            model_name='reg_pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='syc_pizza',
            name='toppings',
        ),
    ]
