# Generated by Django 2.0.3 on 2018-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='small',
            field=models.BooleanField(default=False),
        ),
    ]
