# Generated by Django 2.0.3 on 2018-05-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180502_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='large',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='small',
        ),
    ]
