# Generated by Django 2.0.3 on 2018-05-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_topping_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='quantity',
        ),
    ]
